### ISSUE TITLE
Style the widget

### ISSUE THREAD

**Issue by iamjessklein** [toolness/p5.js-widget#15]
The widget could be styled so that it's designed in thematic harmony with the p5 IDE and website. In order to start this, I broke  down the anatomy of the widget to understand all of the different components and what role they play in terms of provide feedback for users:

![4a34cff2-3e0f-475b-a247-36028af7df6c](https://cloud.githubusercontent.com/assets/535012/14404999/30ed6288-fe52-11e5-9429-69805e0b7dfc.jpg)

**Comment by iamjessklein** [comment]
Building off of the widget that's currently implemented, I did a few iterations on the style.

Here's the current implementation:

<img width="804" alt="screen shot 2016-04-09 at 10 12 29 am" src="https://cloud.githubusercontent.com/assets/535012/14405164/8c12b290-fe56-11e5-880f-4f18202b3581.png">

Here are my first iterations:

Option A:
![widget-a](https://cloud.githubusercontent.com/assets/535012/14405174/d74f4282-fe56-11e5-8055-c6d923d748b4.png)

Option B:
![widget-b](https://cloud.githubusercontent.com/assets/535012/14405175/de2e1682-fe56-11e5-8975-19c97bf51b2b.png)

Option C:
<img width="869" alt="screen shot 2016-04-09 at 1 51 54 pm" src="https://cloud.githubusercontent.com/assets/535012/14405338/b099f8ea-fe5a-11e5-9069-1788064eb497.png">

Please provide feedback on this [invision mockup](https://invis.io/YW6VO7ODA#/149660937_Widgets).

**Comment by iamjessklein** [comment]
Here's what option b would look like in context:
![artboard 5](https://cloud.githubusercontent.com/assets/535012/14406292/ead0a880-fe71-11e5-924a-af813fe0d9ce.png)

**Comment by toolness** [comment]
Option B looks awesome! I thought that #14 was this issue, so all commits related to this referenced that issue instead--so look over there!

I'm going to mark this as fixed, and we can address individual styling bugs in separate issues.
