### ISSUE TITLE
auto-format

### ISSUE THREAD

**Issue by shiffman** [toolness/p5.js-widget#55]
This came up at the p5.js working group meeting via @lmccart.  Might be good to have "auto-format" with CMD-T in the widget (same as current desktop editor.)

**Comment by lmccart** [comment]
or just maybe when it is built and rendered at the start, any example code inside is auto-formatted.

**Comment by toolness** [comment]
Sure!

We can add another option, say, `data-auto-format` to the widget, that enables auto-formatting, or we could enable it by default and have `data-no-auto-format`...

**Comment by toolness** [comment]
Out of curiosity, what's the use case for this? If it's intended primarily for authors, e.g. to workaround issues like #56, then I think there are some [alternative solutions](https://github.com/toolness/p5.js-widget/issues/56#issuecomment-214706271)... If it's to help learners understand what well-formatted code looks like, though, that's cool!

**Comment by lmccart** [comment]
this came up from a discussion we had with @tchoi8 where @shiffman and I were mentioning how it's helpful to use proper formatting in teaching examples. @tchoi8 mentioned that it was difficult to format the text in the widget and so we thought an auto-format call before rendering on the page might be helpful. but looking more closely at what's happening on the wordpress page, it actually looks ok. if you make the example in another editor and then just copy paste it onto the page, you can take advantage of all tab and auto-format capabilities of the editor you're using. so it might be overkill to build it into the widget.

**Comment by toolness** [comment]
Ok cool!

Yeah, one can of worms auto-formatting potentially introduces is, "what *kind* of style should the auto-formatter use?", which I'd love to avoid if at all possible :grin:
