### ISSUE TITLE
Use p5 syntax highlighting colors

### ISSUE THREAD

**Issue by toolness** [toolness/p5.js-widget#6]
They look a lot nicer than the CodeMirror defaults.

**Comment by tchoi8** [comment]
yes. that would be super helpful for the beginners. :)

**Comment by toolness** [comment]
Ok, I fixed this, but because the p5 website uses [prism](http://prismjs.com/) and the widget uses [codemirror](http://codemirror.net), there's some inconsistencies between the two that can't be fixed, which is a bummer.
