### ISSUE TITLE
Add user control of LoopChecker#maxLoopLength limit

### ISSUE THREAD

**Issue by DexterShepherd** [toolness/p5.js-widget#69]
Hey All,

Thanks for the great widget! I recently needed to load a fairly large .obj into a sketch during `preload()` and ran up against the `LoopChecker` killing my sketch before I was able to load the resource. Forking the repo and commenting out the error throwing line in `LoopChecker` fixed the issue. 

Would you be open to a PR adding `data-loopcheck-enable` and/or `data-loopcheck-length` as user configurable parameters on the parent `<script>` element? 

Thanks again,

Dexter

**Comment by toolness** [comment]
Oh that's a great idea! Sure, I'd be happy to accept such a PR, thanks for offering.
