### ISSUE TITLE
Error: URI Too Long

### ISSUE THREAD

**Issue by Craig88** [toolness/p5.js-widget#79]
Hey,

When I use a code fragment that is significantly long I get this error message
"Error: URI Too Long"

Is there a solution for this?

**Comment by Craig88** [comment]
I think I've resolved this by self hosting the widget...

**Comment by AhmadMoussa** [comment]
Sorry to bring this up again, but what do you mean exactly with self hosting the widget? Currently running into the same issue with a rather long chunk of code! Thanks in advance!

**Comment by Craig88** [comment]
Hey @AhmadMoussa - I have installed the p5js-widget on my own web server. I think my administrator also had to adjust a setting on the server to make sure it could cope with a long URI. Hope this helps (sorry it's been a while since I set it up)
